/* eslint-disable @next/next/no-page-custom-font */
// import Document, { Html, Head, Main, NextScript } from "next/document";
import Head from "next/head";
import GameTitle from "../components/GameTitle";
// import Image from "next/image";
import Board from "../containers/Board";
// import * as styles from "../styles/Home.module.css";

export default function Home() {
  return (
    // <div className="container">

    <div>
      <Head>
        <title>Tic Tac Toe By Peter Salter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Capriola&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <GameTitle />
      {/* <main className="main"> */}
      <main>
        <Board />
      </main>
    </div>
  );
}
